-------------------------------------------------------------------------------
Test set: br.com.contmatic.empresa.EnderecoTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec <<< FAILURE!
br.com.contmatic.empresa.EnderecoTest.testar_numero_do_logradouro()  Time elapsed: 0.001 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <java.lang.IllegalArgumentException> but was: <java.lang.NullPointerException>
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:65)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:2920)
	at br.com.contmatic.empresa.EnderecoTest.numero_do_logradouro_nao_deve_passar_de_10000(EnderecoTest.java:107)
	at br.com.contmatic.empresa.EnderecoTest.testar_numero_do_logradouro(EnderecoTest.java:44)
Caused by: java.lang.NullPointerException
	at br.com.contmatic.empresa.EnderecoTest.lambda$numero_do_logradouro_nao_deve_passar_de_10000$9(EnderecoTest.java:108)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
	... 20 more

br.com.contmatic.empresa.EnderecoTest.testar_cep()  Time elapsed: 0 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <java.lang.IllegalArgumentException> but was: <java.lang.NullPointerException>
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:65)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:2920)
	at br.com.contmatic.empresa.EnderecoTest.cep_da_empresa_nao_deve_ser_nulo(EnderecoTest.java:88)
	at br.com.contmatic.empresa.EnderecoTest.testar_cep(EnderecoTest.java:31)
Caused by: java.lang.NullPointerException
	at br.com.contmatic.empresa.EnderecoTest.lambda$cep_da_empresa_nao_deve_ser_nulo$6(EnderecoTest.java:89)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
	... 20 more

br.com.contmatic.empresa.EnderecoTest.testar_uf()  Time elapsed: 0 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <java.lang.IllegalArgumentException> but was: <java.lang.NullPointerException>
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:65)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:2920)
	at br.com.contmatic.empresa.EnderecoTest.uf_da_empresa_nao_deve_ser_nulo(EnderecoTest.java:70)
	at br.com.contmatic.empresa.EnderecoTest.testar_uf(EnderecoTest.java:37)
Caused by: java.lang.NullPointerException
	at br.com.contmatic.empresa.EnderecoTest.lambda$uf_da_empresa_nao_deve_ser_nulo$3(EnderecoTest.java:71)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
	... 20 more

